from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import time

app = FastAPI(title="Java2Cangjie Model Service", version="1.0.0")


class ConvertRequest(BaseModel):
    java_code: str = Field(..., min_length=1, description="待转换 Java 代码")
    max_new_tokens: int = Field(default=512, ge=16, le=4096)
    temperature: float = Field(default=0.1, ge=0.0, le=2.0)


class ConvertResponse(BaseModel):
    cangjie_code: str
    model_name: str
    quantization: str
    latency_ms: int


class ModelRuntime:
    """模拟 LLaMA Factory 的加载与推理流程。"""

    def __init__(self) -> None:
        self.loaded = False
        self.model_name = "java2cangjie-sft"
        self.quantization = "AWQ-4bit"

    def load(self) -> None:
        # 在真实场景中，这里应调用 LLaMA Factory 的模型加载能力
        self.loaded = True

    def infer(self, java_code: str, max_new_tokens: int, temperature: float) -> str:
        if not self.loaded:
            raise RuntimeError("model not loaded")

        # 在真实场景中，这里应调用 LLaMA Factory 推理接口
        wrapped = java_code.strip().replace("\t", "    ")
        return (
            "// Cangjie code generated by quantized model\n"
            "package java2cangjie\n\n"
            "main() {\n"
            "    // 原始 Java 代码（示意）\n"
            + "\n".join(f"    // {line}" for line in wrapped.splitlines())
            + "\n}\n"
        )


runtime = ModelRuntime()
runtime.load()


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "loaded": runtime.loaded, "model": runtime.model_name}


@app.post("/api/v1/convert", response_model=ConvertResponse)
def convert(req: ConvertRequest) -> ConvertResponse:
    if not req.java_code.strip():
        raise HTTPException(status_code=400, detail="java_code 不能为空")

    started = time.time()
    cangjie_code = runtime.infer(req.java_code, req.max_new_tokens, req.temperature)
    latency_ms = int((time.time() - started) * 1000)

    return ConvertResponse(
        cangjie_code=cangjie_code,
        model_name=runtime.model_name,
        quantization=runtime.quantization,
        latency_ms=latency_ms,
    )
